import assert from'node:assert/strict';import fs from'node:fs';
const app=fs.readFileSync(new URL('../js/app.js',import.meta.url),'utf8');
const voice=fs.readFileSync(new URL('../js/voice/voice-search.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../drug-qa-fab.css',import.meta.url),'utf8');
const fab=fs.readFileSync(new URL('../js/ui/drug-qa-fab.js',import.meta.url),'utf8');
assert.match(app,/mountDrugQAFab/);
assert.match(voice,/transcribe\(/);
for(const s of ['qaFab','qaDrawer','qaVoice','语音提问','s.qa.ask'])assert.match(fab,new RegExp(s));
assert.match(css,/\.drug-qa-fab\{/);
assert.match(css,/position:fixed/);
assert.match(css,/right:/);
assert.match(css,/bottom:/);
assert.match(css,/\.drug-qa-drawer/);
console.log('drug QA floating voice tests passed');
