import assert from'node:assert/strict';import fs from'node:fs';
const url=new URL('../drugcard-fluid.css',import.meta.url),css=fs.existsSync(url)?fs.readFileSync(url,'utf8'):'';
assert.match(css,/body\[data-route="drug"\]\{[^}]*--drug-title-fs:clamp\(/);
assert.match(css,/body\[data-route="drug"\]\{[^}]*--drug-body-fs:clamp\(/);
assert.match(css,/body\[data-route="drug"\]\{[^}]*--drug-meta-fs:clamp\(/);
assert.match(css,/body\[data-route="drug"\] \.drug-head h1\{font-size:var\(--drug-title-fs\)!important/);
assert.match(css,/body\[data-route="drug"\] \.info li\{font-size:var\(--drug-body-fs\)!important/);
assert.match(css,/body\[data-route="drug"\] \.source\{[^}]*font-size:var\(--drug-meta-fs\)!important/);
assert.match(css,/body\[data-route="drug"\] \.card-grid\{[^}]*grid-template-columns:repeat\(4,minmax\(0,1fr\)\)/);
assert.match(css,/body\[data-route="drug"\] \.app-sidebar\{display:flex!important/);
assert.match(css,/body\[data-route="drug"\] \.app-topbar\{display:grid!important/);
console.log('drug card fluid landscape typography tests passed');
