import assert from'node:assert/strict';import fs from'node:fs';
const cleanup=fs.readFileSync(new URL('../js/ui/home-cleanup.js',import.meta.url),'utf8');
const qa=fs.readFileSync(new URL('../js/ui/drug-qa-fab.js',import.meta.url),'utf8');
const drugs=fs.readFileSync(new URL('../data/drugs.js',import.meta.url),'utf8');
assert.match(cleanup,/hero-workflow/,'home hero should be replaced by neutral workflow visual');
assert.ok(!cleanup.includes('BRENTUX_50.svg'),'home cleanup must not use a specific drug image');
assert.match(qa,/host\.hidden/,'QA host must be route-gated');
assert.match(qa,/dataset\.route===['"]drug['"]/,'QA host must only show on drug route');
assert.match(drugs,/BRENTUX_50_PLACEHOLDER\.svg/,'Brentuximab base image must use cache-safe placeholder');
console.log('home hero and QA visibility tests passed');
