import{Evidence}from'../agent/evidence.js';
const now=()=>new Date().toISOString(),clone=x=>JSON.parse(JSON.stringify(x));
export class KnowledgeService{
  constructor(storage=globalThis.localStorage){this.storage=storage;this.draftsKey='pivas3:drafts';this.pubKey='pivas3:published'}
  read(k){try{return JSON.parse(this.storage?.getItem(k)||'[]')}catch{return[]}}
  write(k,v){this.storage?.setItem(k,JSON.stringify(v));return v}
  createDraft(payload){const drafts=this.read(this.draftsKey),stamp=Date.now(),item={...payload,id:payload.id||`draft_${stamp}_${Math.random().toString(36).slice(2,7)}`,drugId:payload.drugId||`USER_${stamp}`,status:'draft',createdAt:now(),updatedAt:now()};drafts.unshift(item);this.write(this.draftsKey,drafts);return clone(item)}
  updateDraft(id,patch={}){const drafts=this.read(this.draftsKey),item=drafts.find(x=>x.id===id);if(!item)throw new Error('draft not found');Object.assign(item,clone(patch),{updatedAt:now()});if(item.status==='approved')item.status='draft';this.write(this.draftsKey,drafts);return clone(item)}
  resolveConflicts(id,{reviewer,note}={}){const drafts=this.read(this.draftsKey),item=drafts.find(x=>x.id===id);if(!item)throw new Error('draft not found');const ev=item.evidence||(item.evidence={}),conflicts=[...(ev.conflicts||[])];if(!conflicts.length)return clone(item);ev.conflictResolutions=[...(ev.conflictResolutions||[]),{conflicts,reviewer:reviewer||'pharmacist',note:note||'人工核对后确认最终字段',resolvedAt:now()}];ev.conflicts=[];item.status='draft';item.updatedAt=now();this.write(this.draftsKey,drafts);return clone(item)}
  review(id,{approved,reviewer}){const drafts=this.read(this.draftsKey),item=drafts.find(x=>x.id===id);if(!item)throw new Error('draft not found');item.status=approved?'approved':'rejected';item.reviewer=reviewer||'pharmacist';item.reviewedAt=now();this.write(this.draftsKey,drafts);return clone(item)}
  publish(id){const drafts=this.read(this.draftsKey),item=drafts.find(x=>x.id===id);if(!item)throw new Error('draft not found');if(item.status!=='approved')throw new Error('draft must be approved before publish');const check=Evidence.validateDraft(item);if(!check.canPublish)throw new Error(check.blockers.some(x=>x.startsWith('conflict'))?'conflict blocks publish':check.blockers.includes('drug-photo-required')?'drug photo required':'primary evidence required');const published=this.read(this.pubKey),prev=published.filter(x=>x.drugId===item.drugId||x.name===item.name),version=Math.max(0,...prev.map(x=>Number(x.version)||0))+1,out={...clone(item),publicationId:`pub_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,status:'published',version,publishedAt:now()};published.unshift(out);this.write(this.pubKey,published);return clone(out)}
  listDrafts(){return clone(this.read(this.draftsKey))}
  listPublished(){return clone(this.read(this.pubKey))}
  listVersions(key){return this.listPublished().filter(x=>x.drugId===key||x.name===key).sort((a,b)=>(b.version||0)-(a.version||0))}
  rollback(publicationId,{reviewer}={}){const published=this.read(this.pubKey),source=published.find(x=>x.publicationId===publicationId||x.id===publicationId);if(!source)throw new Error('published version not found');const same=published.filter(x=>x.drugId===source.drugId||x.name===source.name),version=Math.max(0,...same.map(x=>Number(x.version)||0))+1,out={...clone(source),publicationId:`pub_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,status:'published',version,reviewer:reviewer||source.reviewer||'pharmacist',reviewedAt:now(),publishedAt:now(),rolledBackFrom:source.version};published.unshift(out);this.write(this.pubKey,published);return clone(out)}
  exportBundle(){return{schema:'pivas-demo-knowledge-v1',exportedAt:now(),drafts:this.listDrafts(),published:this.listPublished()}}
  importBundle(bundle={}){if(bundle.schema!=='pivas-demo-knowledge-v1')throw new Error('不支持的知识库文件格式');const merge=(current,incoming)=>{const map=new Map(current.map(x=>[x.publicationId||x.id||`${x.drugId}:${x.version}`,x]));for(const x of incoming||[])map.set(x.publicationId||x.id||`${x.drugId}:${x.version}`,clone(x));return[...map.values()]};this.write(this.draftsKey,merge(this.read(this.draftsKey),bundle.drafts||[]));this.write(this.pubKey,merge(this.read(this.pubKey),bundle.published||[]));return{drafts:this.listDrafts().length,published:this.listPublished().length}}
}
