import{MaterialParser}from'../agent/material-parser.js';
import{PhotoProcessor}from'../agent/photo-processor.js';
import{DualCardGenerator}from'../agent/dual-card-generator.js';
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
export function mountAIBuilder(root,s){
 const section=root.querySelector('[data-view="builder"]');if(!section)return;
 let materials=[],photos=[],activeDraft=null;
 section.innerHTML=`<div class="bar"><button data-builder-home>← 返回</button><h2>AI自动建卡</h2></div><div class="builder-v31"><div class="panel box"><div class="step-title"><span>1</span><div><h3>说明书 / 药物资料 <b class="required">必需</b></h3><p>用于生成调配、稳定性、输注和警示等临床字段。</p></div></div><div class="upload-actions"><button id="materialCapture">📷 拍照资料</button><button id="materialUpload">⬆ 上传文件</button></div><input id="materialCaptureInput" class="hidden-input" type="file" accept="image/*" capture="environment"><input id="materialUploadInput" class="hidden-input" type="file" accept=".pdf,.txt,.md,image/*" multiple><div id="materialList" class="upload-list muted">尚未添加资料</div></div><div class="panel box"><div class="step-title"><span>2</span><div><h3>药物照片 <b class="required">至少1张</b></h3><p>用于识别药名、商品名、规格、剂型、厂家，并作为知识卡图片。</p></div></div><div class="upload-actions"><button id="drugCapture">📷 拍照药物</button><button id="drugUpload">⬆ 上传照片</button></div><input id="drugCaptureInput" class="hidden-input" type="file" accept="image/*" capture="environment"><input id="drugUploadInput" class="hidden-input" type="file" accept="image/*" multiple><div id="photoPreview" class="photo-preview"><span class="muted">尚未添加药物照片</span></div><p class="muted">至少1张；建议追加标签面/背面照片提高识别可靠性。</p></div><div class="panel box builder-wide"><div class="step-title"><span>3</span><div><h3>AI联合分析</h3><p>主资料决定临床字段；药物照片用于身份确认和交叉核对。</p></div></div><div class="meta-grid"><input id="builderNameV31" placeholder="药品名称（可留空让AI识别）"><input id="builderStrengthV31" placeholder="规格（可留空让AI识别）"></div><button id="builderGenerateV31" class="primary big" disabled>AI自动分析并生成知识卡</button><div id="builderStateV31" class="evidence">请先完成前两项必需输入。</div></div><div class="panel box builder-wide"><div class="step-title"><span>4</span><div><h3>Draft / 药师审核</h3><p>发现药名、规格、剂型或厂家冲突时禁止发布。</p></div></div><div id="conflictState" class="conflict-box" hidden></div><textarea id="draftJsonV31" rows="16" readonly placeholder="AI生成的结构化Draft会显示在这里"></textarea><input id="reviewerV31" placeholder="审核药师"><div class="actions"><button id="approveDraftV31">审核通过</button><button id="rejectDraftV31">退回</button><button id="publishDraftV31" class="primary">发布知识库</button></div></div></div>`;
 const q=id=>section.querySelector('#'+id),state=q('builderStateV31'),generate=q('builderGenerateV31'),materialList=q('materialList'),preview=q('photoPreview');
 const toast=m=>{const t=root.querySelector('#toast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
 const addUnique=(arr,files)=>{for(const f of Array.from(files||[]))if(!arr.some(x=>x.name===f.name&&x.size===f.size))arr.push(f)};
 function sync(){materialList.innerHTML=materials.length?materials.map(f=>`<span class="file-chip">${esc(f.name)}</span>`).join(''):'<span class="muted">尚未添加资料</span>';preview.innerHTML=photos.length?photos.map((f,i)=>`<figure><img src="${URL.createObjectURL(f)}" alt="药物照片${i+1}"><figcaption>${esc(f.name)}</figcaption></figure>`).join(''):'<span class="muted">尚未添加药物照片</span>';generate.disabled=!(materials.length&&photos.length);state.textContent=generate.disabled?'说明书/药物资料与至少1张药物照片均为必需。':`已就绪：${materials.length}份资料 + ${photos.length}张药物照片`}
 q('materialCapture').onclick=()=>q('materialCaptureInput').click();q('materialUpload').onclick=()=>q('materialUploadInput').click();q('drugCapture').onclick=()=>q('drugCaptureInput').click();q('drugUpload').onclick=()=>q('drugUploadInput').click();
 q('materialCaptureInput').onchange=e=>{addUnique(materials,e.target.files);sync()};q('materialUploadInput').onchange=e=>{addUnique(materials,e.target.files);sync()};q('drugCaptureInput').onchange=e=>{addUnique(photos,e.target.files);sync()};q('drugUploadInput').onchange=e=>{addUnique(photos,e.target.files);sync()};
 section.querySelector('[data-builder-home]').onclick=()=>s.router.go('home');
 generate.onclick=async()=>{try{generate.disabled=true;state.textContent='正在解析说明书/药物资料…';const material=await MaterialParser.parseFiles(materials,{onProgress:p=>state.textContent=p.status==='ocr'?`OCR资料：${p.source}`:`解析资料 ${p.index||''}/${p.total||''} ${p.source||''}`});state.textContent='正在处理药物照片并识别包装文字…';const processed=await PhotoProcessor.process(photos,{onProgress:p=>state.textContent=p.status==='ocr'?`OCR药物照片 ${p.index}/${p.total}`:`处理药物照片 ${p.index}/${p.total}`});state.textContent='正在进行AI联合分析与一致性校验…';const draftPayload=await DualCardGenerator.generate({material,photos:processed,metadata:{name:q('builderNameV31').value.trim(),strength:q('builderStrengthV31').value.trim()},apiConfig:s.store.readJson('api',{})});activeDraft=s.knowledge.createDraft(draftPayload);renderDraft();state.textContent='DRAFT 已生成，等待药师审核'}catch(e){state.textContent='失败：'+e.message}finally{sync()}};
 function displayDraft(d){if(!d)return'';const copy=JSON.parse(JSON.stringify(d));if(copy.image)copy.image='[药物照片已保存]';return JSON.stringify(copy,null,2)}
 function renderDraft(){q('draftJsonV31').value=displayDraft(activeDraft);const c=activeDraft?.evidence?.conflicts||[],box=q('conflictState');box.hidden=!c.length;box.textContent=c.length?'⚠ 检测到冲突：'+c.join('、')+'。需药师核对后修正，当前禁止发布。':''}
 q('approveDraftV31').onclick=()=>review(true);q('rejectDraftV31').onclick=()=>review(false);
 function review(ok){if(!activeDraft)return toast('请先生成Draft');try{activeDraft=s.knowledge.review(activeDraft.id,{approved:ok,reviewer:q('reviewerV31').value.trim()||'pharmacist'});renderDraft();toast(ok?'已审核通过':'已退回')}catch(e){toast(e.message)}}
 q('publishDraftV31').onclick=()=>{if(!activeDraft)return toast('请先生成Draft');try{const p=s.knowledge.publish(activeDraft.id);if(p.drugId&&p.name)s.repo.upsert({...p,id:p.drugId});state.textContent=`已发布 v${p.version}；正式临床使用前仍需核对现行说明书/院内规则`;toast('已发布知识库')}catch(e){toast('不能发布：'+e.message)}};
 sync();
}
