const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const icons={home:'<path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10.5V20h13v-9.5M9 20v-6h6v6"/>',scan:'<path d="M4 7V5a2 2 0 0 1 2-2h2M16 3h2a2 2 0 0 1 2 2v2M20 17v2a2 2 0 0 1-2 2h-2M8 21H6a2 2 0 0 1-2-2v-2"/><rect x="7" y="8" width="10" height="8" rx="2"/><circle cx="12" cy="12" r="2.2"/>',search:'<circle cx="11" cy="11" r="6.5"/><path d="m16 16 4.5 4.5"/>',voice:'<rect x="9" y="3" width="6" height="11" rx="3"/><path d="M5.5 11.5a6.5 6.5 0 0 0 13 0M12 18v3M9 21h6"/>',knowledge:'<ellipse cx="12" cy="5" rx="7" ry="3"/><path d="M5 5v6c0 1.7 3.1 3 7 3s7-1.3 7-3V5M5 11v6c0 1.7 3.1 3 7 3s7-1.3 7-3v-6"/>',builder:'<path d="M5 3h10l4 4v14H5z"/><path d="M15 3v5h4M9 13h6M12 10v6"/>',history:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3.5 2"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1A1.7 1.7 0 0 0 9 4.6 1.7 1.7 0 0 0 10 3V2.8h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1z"/>',chev:'<path d="m9 6 6 6-6 6"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',shield:'<path d="M12 3 5 6v5c0 4.7 2.9 8.1 7 10 4.1-1.9 7-5.3 7-10V6z"/><path d="m9.5 12 1.7 1.7 3.6-4"/>'};
const icon=(name,cls='')=>`<svg class="ui-icon ${cls}" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${icons[name]||icons.home}</svg>`;
const nav=[['home','home','首页'],['scan','scan','扫描识药'],['builder','builder','AI建卡'],['knowledge','knowledge','药品知识库'],['search','search','手动搜索'],['voice','voice','语音搜药'],['history','history','使用历史'],['settings','settings','系统设置']];
export function mountV31Shell(root,s){
 const oldTop=root.querySelector('.top');if(oldTop)oldTop.classList.add('legacy-top');const main=root.querySelector('main');if(!main)return;
 root.insertAdjacentHTML('afterbegin',`<aside class="app-sidebar"><div class="side-brand"><div class="brand-mark">${icon('shield')}</div><div class="brand-text"><b>PIVAS</b><span>智能用药助手</span></div></div><nav class="side-nav" aria-label="主导航">${nav.map(([id,ic,label])=>`<button class="side-nav-item" data-v31-target="${id}" aria-label="${label}">${icon(ic)}<span class="nav-label">${label}</span></button>`).join('')}</nav><div class="side-foot"><span class="status-dot"></span><div><b>系统正常</b><small>Demo 3.1</small></div></div></aside><header class="app-topbar"><div class="top-brand"><strong>PIVAS 智能用药助手 <em>3.1</em></strong><span>浙江大学医学院附属邵逸夫医院 · 药学部</span></div><form class="top-search" id="v31TopSearch"><span>${icon('search')}</span><input id="v31TopSearchInput" placeholder="搜索药品（通用名 / 商品名 / 英文名）" autocomplete="off"><button type="submit" aria-label="搜索">${icon('search')}</button></form><div class="top-actions"><button class="icon-button" type="button" aria-label="通知">${icon('bell')}</button><div class="user-chip">${icon('user')}<span><b>药师</b><small>PIVAS · Demo</small></span></div></div></header>`);
 main.classList.add('app-main');root.insertAdjacentHTML('beforeend',`<footer class="app-footer"><span><b>PIVAS 智能用药助手 3.1</b> · Demo</span><span>药学部 · 静脉用药调配中心</span><span class="footer-status"><i></i>系统正常运行</span></footer>`);
 const triggerRoute=id=>{const candidates=[...root.querySelectorAll(`[data-go="${id}"]`)];const btn=candidates.find(x=>x.isConnected);btn?.click()};
 root.querySelectorAll('[data-v31-target]').forEach(b=>b.onclick=()=>triggerRoute(b.dataset.v31Target));
 const topForm=root.querySelector('#v31TopSearch');topForm.onsubmit=e=>{e.preventDefault();const q=root.querySelector('#v31TopSearchInput').value.trim();triggerRoute('search');const input=root.querySelector('#searchQ');if(input){input.value=q;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus()}};
 decorateHome();
 function decorateHome(){const home=root.querySelector('[data-view="home"]'),hero=home?.querySelector('.hero'),tiles=home?.querySelector('.tiles');if(!home||!hero||!tiles)return;
 hero.innerHTML=`<div class="hero-copy"><h1>PIVAS 智能用药助手</h1><p>面向静脉用药调配场景，把识药、知识卡、AI建卡和药师审核连接成一个可靠工作流。</p><div class="hero-points"><span>${icon('shield')}安全优先</span><span>证据可追溯</span><span>药师审核</span></div></div><div class="hero-visual" aria-hidden="true"><div class="hero-halo"></div><img src="./assets/BRENTUX_50.svg" alt=""><div class="hero-note"><b>精准识药</b><span>快速 · 清晰 · 可核对</span></div></div>`;
 const primary=new Set(['scan','builder','knowledge']);tiles.querySelectorAll('.tile').forEach(t=>{const id=t.dataset.go;t.classList.toggle('primary-tile',primary.has(id));t.classList.toggle('secondary-tile',!primary.has(id));const i=t.querySelector('i');if(i)i.innerHTML=icon(id==='builder'?'builder':id==='knowledge'?'knowledge':id==='history'?'history':id==='settings'?'settings':id==='voice'?'voice':id==='search'?'search':'scan');if(primary.has(id)){const arrow=document.createElement('span');arrow.className='tile-arrow';arrow.innerHTML=icon('chev');t.appendChild(arrow)}});
 const dash=document.createElement('div');dash.className='home-dashboard';dash.innerHTML=`<section class="metric-strip panel" id="v31Metrics"></section><section class="common-drugs panel"><div class="section-head"><div><h2>常用药品</h2><p>Demo知识库中的快速入口</p></div><button type="button" data-v31-more="knowledge">查看全部 ${icon('chev')}</button></div><div class="drug-rail" id="v31DrugRail"></div></section><section class="recent-activity panel"><div class="section-head"><div><h2>最新动态</h2><p>本机操作记录</p></div><button type="button" data-v31-more="history">全部记录 ${icon('chev')}</button></div><div class="activity-list" id="v31Activity"></div></section>`;tiles.after(dash);dash.querySelectorAll('[data-v31-more]').forEach(b=>b.onclick=()=>triggerRoute(b.dataset.v31More));refreshHome()}
 function refreshHome(){const metrics=root.querySelector('#v31Metrics'),rail=root.querySelector('#v31DrugRail'),activity=root.querySelector('#v31Activity');if(!metrics||!rail||!activity)return;const drugs=s.repo.list(),drafts=s.knowledge.listDrafts?.()||[],published=s.knowledge.listPublished?.()||[],history=s.store.readJson('history',[]),pending=drafts.filter(x=>x.status==='draft'||x.status==='rejected').length,latestMap=new Map();published.forEach(x=>{const k=x.drugId||x.name,cur=latestMap.get(k);if(!cur||(x.version||0)>(cur.version||0))latestMap.set(k,x)});metrics.innerHTML=[[drugs.length,'已收录药品','knowledge'],[pending,'待审核','builder'],[latestMap.size,'已发布','knowledge'],[history.length,'本机操作','history']].map(([n,label,target])=>`<button class="metric" data-metric="${target}"><b>${n}</b><span>${label}</span></button>`).join('');metrics.querySelectorAll('[data-metric]').forEach(b=>b.onclick=()=>triggerRoute(b.dataset.metric));rail.innerHTML=drugs.slice(0,4).map(d=>`<button class="drug-mini" data-v31-drug="${esc(d.id)}"><div class="drug-mini-img"><img src="${esc(d.image||'')}" alt="${esc(d.name)}"></div><b>${esc(d.name)}</b><span>${esc(d.brand||'')}</span><small>${esc(d.strength||'')}</small><em>查看药卡 ${icon('chev')}</em></button>`).join('');rail.querySelectorAll('[data-v31-drug]').forEach(b=>b.onclick=()=>openDrugViaSearch(b.dataset.v31Drug));const rows=history.slice(0,5);activity.innerHTML=rows.length?rows.map((x,i)=>`<div class="activity-item"><i class="activity-dot a${i%3}"></i><div><b>${esc(x.type)}</b><span>${esc(x.detail||'')}</span></div><time>${new Date(x.time).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})}</time></div>`).join(''):`<div class="empty-state"><span>${icon('history')}</span><b>暂无操作记录</b><small>打开药卡或创建知识卡后，这里会显示最近动态。</small></div>`}
 function openDrugViaSearch(id){const d=s.repo.get(id);if(!d)return;triggerRoute('search');const input=root.querySelector('#searchQ');if(!input)return;input.value=d.name;input.dispatchEvent(new Event('input',{bubbles:true}));setTimeout(()=>[...root.querySelectorAll('#searchResults [data-drug]')].find(x=>x.dataset.drug===id)?.click(),0)}
 function updateActive(){const visible=[...main.querySelectorAll('[data-view]')].find(x=>!x.hidden),id=visible?.dataset.view||'home';root.querySelectorAll('[data-v31-target]').forEach(b=>b.classList.toggle('active',b.dataset.v31Target===id));if(id==='home')refreshHome();document.body.dataset.route=id}
 const observer=new MutationObserver(updateActive);main.querySelectorAll('[data-view]').forEach(x=>observer.observe(x,{attributes:true,attributeFilter:['hidden']}));updateActive();
}
