import{DrugCard}from'../drugs/drug-card.js';import{VoiceSearch}from'../voice/voice-search.js';import{testApiConnection}from'../core/api-client.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
export function mountViews(root,s){
 let scan=null;const toast=m=>{const t=root.querySelector('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)},log=s.log||(()=>{});
 root.innerHTML=`<header class="top"><div><b>PIVAS 智能用药助手</b><span>3.0.2 · 原生 ES Modules</span></div><span>本地知识优先 · AI输出需药师审核</span></header><main>
 <section data-view="home"><div class="hero panel"><div><h1>PIVAS 智能用药助手 3.0</h1><p>识药、药卡、语音、AI建卡与知识审核统一工作台</p></div><span class="pill">HTTPS Demo</span></div><div class="tiles">${[['scan','📷','扫描 / OCR识药','进入后自动启动 · 条码/OCR统一匹配'],['search','⌕','手动搜索','药名、商品名、英文名、规格'],['voice','🎙','语音搜药','高置信度直接弹卡，低置信度显示候选'],['knowledge','▤','药品知识库','基础药卡 + 版本历史 + 导入导出'],['builder','＋','AI自动建卡 / 审核','资料 + 药物照片 → AI分析 → Draft → 药师审核'],['settings','⚙','AI / API设置','连接测试、超时与视觉输入设置'],['history','◷','使用历史','不保存患者信息']].map(x=>`<button class="tile panel" data-go="${x[0]}"><i>${x[1]}</i><b>${x[2]}</b><span>${x[3]}</span></button>`).join('')}</div></section>
 <section data-view="scan" hidden><div class="bar"><button data-go="home">← 返回</button><h2>扫描 / OCR识药</h2></div><div class="scan-layout"><div class="camera panel"><video id="scanVideo" playsinline muted></video><div class="frame"></div><div class="scanline"></div></div><div class="side"><div class="panel box"><h3>状态</h3><div id="scanState">进入本页后自动启动</div><div class="actions"><button id="scanStart" class="primary">重新开始</button><button id="camSwitch">切换前/后摄像头</button><button id="scanStop">停止</button></div></div><div class="panel box"><h3>条码 / 多帧证据</h3><div id="scanEvidence" class="evidence">暂无</div></div><div class="panel box"><h3>候选</h3><div id="scanCandidates"></div></div></div></div></section>
 <section data-view="search" hidden><div class="bar"><button data-go="home">← 返回</button><h2>手动搜索</h2></div><div class="panel search"><input id="searchQ" placeholder="例如：维布妥昔、安维汀、500mg"><div id="searchResults"></div></div></section>
 <section data-view="voice" hidden><div class="bar"><button data-go="home">← 返回</button><h2>语音搜药</h2></div><div class="panel centered"><div class="voice-orb">🎙</div><button id="voiceStart" class="primary">开始说话</button><div id="voiceText" class="evidence">等待语音</div><div id="voiceResults"></div></div></section>
 <section data-view="drug" hidden><div class="bar"><button data-go="home">← 返回</button><h2>药品信息</h2></div><div id="drugCard"></div><div class="panel qa"><h3>当前药品 AI 问答</h3><div class="actions"><button data-q="怎么配？">怎么配？</button><button data-q="保存多久？">保存多久？</button><button data-q="输注要求？">输注要求</button><button data-q="注意事项？">注意事项</button></div><div class="qa-row"><input id="qaInput" placeholder="输入当前药品问题"><button id="qaAsk" class="primary">发送</button></div><div id="qaAnswer" class="answer"></div></div></section>
 <section data-view="knowledge" hidden><div class="bar"><button data-go="home">← 返回</button><h2>药品知识库</h2></div><div class="panel box"><div class="knowledge-toolbar"><button id="exportKnowledge">导出知识库</button><button id="importKnowledge">导入知识库</button><input id="importKnowledgeInput" type="file" accept="application/json,.json" hidden></div><div id="knowledgeList" class="list"></div><div id="versionPanel" class="version-panel"></div></div></section>
 <section data-view="builder" hidden></section>
 <section data-view="settings" hidden><div class="bar"><button data-go="home">← 返回</button><h2>AI / API设置</h2></div><div class="panel settings"><label>Base URL<input id="apiBase"></label><label>API Key<input id="apiKey" type="password"></label><label>Model<input id="apiModel"></label><label>Temperature<input id="apiTemp" type="number" value="0" min="0" max="2" step="0.1"></label><label>Timeout (ms)<input id="apiTimeout" type="number" value="30000" min="3000" step="1000"></label><label><input id="apiEnabled" type="checkbox"> 启用外部AI</label><label><input id="apiVision" type="checkbox" checked> 启用视觉输入（AI建卡需要）</label><div class="actions"><button id="apiSave" class="primary">保存到本机</button><button id="apiTest">测试连接</button></div><div id="apiStatus" class="evidence">尚未测试</div><div class="warning">Demo Key仅保存在本机浏览器；正式APP建议接医院网关/安全存储。</div></div></section>
 <section data-view="history" hidden><div class="bar"><button data-go="home">← 返回</button><h2>使用历史</h2></div><div id="historyList" class="panel list"></div></section></main><div id="toast" class="toast"></div>`;
 const renderCandidates=(box,rows)=>{box.innerHTML=(rows||[]).filter(x=>x.score>.2).slice(0,5).map(x=>`<button class="result-row" data-drug="${x.drug.id}"><span><b>${esc(x.drug.name)}</b><small>${esc(x.drug.brand||'')} · ${esc(x.drug.strength)}</small></span><em>${Math.round(x.score*100)}%</em></button>`).join('')||'<p class="muted">暂无可靠候选</p>';box.querySelectorAll('[data-drug]').forEach(b=>b.onclick=()=>openDrug(b.dataset.drug))};
 const stopScan=()=>{s.scan.stop();s.camera.stop();scan=null};
 const goTo=id=>{if(s.router.current==='scan'&&id!=='scan')stopScan();s.router.go(id);if(id==='scan')setTimeout(()=>startScan(),0);if(id==='knowledge')renderKnowledge();if(id==='history')renderHistory();if(id==='settings')loadApi()};
 const openDrug=id=>{const d=s.repo.get(id);if(!d)return;s.qa.setDrug(d);root.querySelector('#drugCard').innerHTML=DrugCard.render(d);goTo('drug');log('打开药品卡',id)};
 root.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>goTo(b.dataset.go));
 root.querySelector('#searchQ').oninput=e=>renderCandidates(root.querySelector('#searchResults'),s.resolver.resolve(e.target.value));
 root.querySelector('#voiceStart').onclick=()=>VoiceSearch.start({onText:t=>root.querySelector('#voiceText').textContent=t,onCandidates:r=>{if(s.resolver.shouldAutoLock(r)){openDrug(r[0].drug.id);toast('语音高置信度匹配，已打开药卡')}else renderCandidates(root.querySelector('#voiceResults'),r)},onError:e=>toast(e.message)});
 async function startScan(){try{const video=root.querySelector('#scanVideo');root.querySelector('#scanState').textContent='正在申请摄像头权限…';await s.camera.start(video);root.querySelector('#scanState').textContent='扫描中（自动启动）';scan=s.scan;scan.start(video,{onBarcode:raw=>{root.querySelector('#scanEvidence').textContent=`条码：${raw}`;const exact=s.repo.get(raw);if(exact){openDrug(exact.id);toast('条码匹配，已打开药卡');return}const r=s.resolver.resolve(raw).slice(0,4);renderCandidates(root.querySelector('#scanCandidates'),r);if(s.resolver.shouldAutoLock(r)){openDrug(r[0].drug.id);toast('条码匹配，已打开药卡')}else root.querySelector('#scanState').textContent=r.length?'条码已识别，请确认候选':'条码已识别，但知识库暂无映射'},onEvidence:e=>root.querySelector('#scanEvidence').textContent=e,onCandidates:r=>renderCandidates(root.querySelector('#scanCandidates'),r),onMatch:r=>{openDrug(r.drug.id);toast('OCR高置信度匹配，已打开药卡')},onProgress:p=>root.querySelector('#scanState').textContent='OCR '+Math.round(p*100)+'%',onError:e=>root.querySelector('#scanState').textContent=e.message})}catch(e){root.querySelector('#scanState').textContent='摄像头启动失败：'+e.message}}
 root.querySelector('#scanStart').onclick=startScan;root.querySelector('#camSwitch').onclick=async()=>{try{await s.camera.switch();s.scan.stop();s.scan.start(root.querySelector('#scanVideo'),scan?.callbacks||{});toast(s.camera.facingMode==='user'?'已切前置':'已切后置')}catch(e){toast(e.message)}};root.querySelector('#scanStop').onclick=()=>{stopScan();root.querySelector('#scanState').textContent='已停止'};
 root.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>ask(b.dataset.q));root.querySelector('#qaAsk').onclick=()=>ask(root.querySelector('#qaInput').value);async function ask(q){if(!q.trim())return;try{root.querySelector('#qaAnswer').textContent='处理中…';root.querySelector('#qaAnswer').textContent=await s.qa.ask(q,s.store.readJson('api',{}))}catch(e){root.querySelector('#qaAnswer').textContent='AI调用失败：'+e.message+'；本地回答：'+s.qa.askLocal(q)}}
 function latestPublished(){const rows=s.knowledge.listPublished(),map=new Map();for(const p of rows){const k=p.drugId||p.name,cur=map.get(k);if(!cur||(p.version||0)>(cur.version||0))map.set(k,p)}return[...map.values()]}
 function renderKnowledge(){const base=s.repo.list(),published=latestPublished(),seen=new Set(),rows=[];for(const d of [...published,...base]){const key=d.drugId||d.id||d.name;if(seen.has(key))continue;seen.add(key);rows.push(d)}root.querySelector('#knowledgeList').innerHTML=rows.map(d=>{const key=d.drugId||d.id||d.name;return`<div class="knowledge-row"><button class="result-row knowledge-open" data-drug="${esc(d.id||d.drugId||'')}"><span><b>${esc(d.name)}</b><small>${esc(d.brand||'')} · ${esc(d.strength||'')} · ${d.status==='published'?'已发布 v'+d.version:'基础库'}</small></span></button><button class="version-btn" data-versions="${esc(key)}">版本历史</button></div>`}).join('');root.querySelectorAll('.knowledge-open[data-drug]').forEach(b=>b.onclick=()=>openDrug(b.dataset.drug));root.querySelectorAll('[data-versions]').forEach(b=>b.onclick=()=>showVersions(b.dataset.versions))}
 function versionDiff(v,prev){if(!prev)return'首版，无上一版可比较。';const fields=['name','brand','en','strength','dosageForm','maker','prep','final','storage','infusion','warnings'],labels={name:'药品名称',brand:'商品名',en:'英文名',strength:'规格',dosageForm:'剂型',maker:'厂家',prep:'调配/复溶',final:'终浓度',storage:'稳定性/贮存',infusion:'输注/输液器',warnings:'关键提醒'},changes=[];for(const f of fields){const a=JSON.stringify(prev[f]??''),b=JSON.stringify(v[f]??'');if(a!==b)changes.push(`${labels[f]}：${String(prev[f]??'—')} → ${String(v[f]??'—')}`)}return changes.length?changes.join('\n'):'与上一版相比，知识卡字段无变化。'}
 function showVersions(key){const vs=s.knowledge.listVersions(key),box=root.querySelector('#versionPanel');box.innerHTML=`<h3>版本历史</h3>`+(vs.length?vs.map((v,i)=>`<div class="version-row"><span><b>v${v.version}</b> · ${esc(v.name||'')} · ${new Date(v.publishedAt).toLocaleString()}${v.rolledBackFrom?` · 回滚自 v${v.rolledBackFrom}`:''}</span><div class="actions"><button data-diff="${i}">版本差异</button><button data-rollback="${esc(v.publicationId||v.id)}">回滚为新版本</button></div></div>`).join('')+'<div id="versionDiff" class="evidence">选择“版本差异”查看与上一版的字段变化。</div>':'<p class="muted">该药暂无已发布历史版本。</p>');box.querySelectorAll('[data-diff]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.diff),v=vs[i],prev=vs.find(x=>Number(x.version)===Number(v.version)-1);box.querySelector('#versionDiff').textContent=`v${v.version} 与上一版：\n${versionDiff(v,prev)}`});box.querySelectorAll('[data-rollback]').forEach(b=>b.onclick=()=>{try{const p=s.knowledge.rollback(b.dataset.rollback,{reviewer:'pharmacist'});if(p.drugId&&p.name)s.repo.upsert({...p,id:p.drugId});log('回滚知识卡',`${p.name}→v${p.version}`);renderKnowledge();showVersions(p.drugId||p.name);toast('已回滚并生成新版本')}catch(e){toast(e.message)}})}
 root.querySelector('#exportKnowledge').onclick=()=>{const blob=new Blob([JSON.stringify(s.knowledge.exportBundle(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`pivas-knowledge-${Date.now()}.json`;a.click();URL.revokeObjectURL(a.href);log('导出知识库','JSON');toast('知识库已导出')};root.querySelector('#importKnowledge').onclick=()=>root.querySelector('#importKnowledgeInput').click();root.querySelector('#importKnowledgeInput').onchange=async e=>{try{const f=e.target.files?.[0];if(!f)return;const result=s.knowledge.importBundle(JSON.parse(await f.text()));for(const p of latestPublished())if(p.drugId&&p.name)s.repo.upsert({...p,id:p.drugId});log('导入知识库',`${result.published} published`);renderKnowledge();toast('知识库导入完成')}catch(err){toast('导入失败：'+err.message)}finally{e.target.value=''}};
 function renderHistory(){const h=s.store.readJson('history',[]);root.querySelector('#historyList').innerHTML=h.length?h.map(x=>`<div class="history-row"><b>${esc(x.type)}</b><span>${new Date(x.time).toLocaleString()} · ${esc(x.detail||'')}</span></div>`).join(''):'<p class="muted">暂无记录。本页不保存患者信息。</p>'}
 function loadApi(){const a=s.store.readJson('api',{});root.querySelector('#apiBase').value=a.base||'';root.querySelector('#apiKey').value=a.key||'';root.querySelector('#apiModel').value=a.model||'';root.querySelector('#apiTemp').value=a.temperature??0;root.querySelector('#apiTimeout').value=a.timeout??30000;root.querySelector('#apiEnabled').checked=!!a.enabled;root.querySelector('#apiVision').checked=a.visionEnabled!==false}
 const currentApi=()=>({base:root.querySelector('#apiBase').value.trim(),key:root.querySelector('#apiKey').value.trim(),model:root.querySelector('#apiModel').value.trim(),temperature:Number(root.querySelector('#apiTemp').value||0),timeout:Number(root.querySelector('#apiTimeout').value||30000),enabled:root.querySelector('#apiEnabled').checked,visionEnabled:root.querySelector('#apiVision').checked});
 root.querySelector('#apiSave').onclick=()=>{s.store.writeJson('api',currentApi());toast('API设置已保存到本机')};root.querySelector('#apiTest').onclick=async()=>{const box=root.querySelector('#apiStatus');try{box.textContent='测试连接中…';const msg=await testApiConnection(currentApi());box.textContent='连接成功：'+msg;toast('API连接成功')}catch(e){box.textContent='连接失败：'+e.message}};
}
