(()=>{
const quick={
ATEZO:{prep:['抽取所需浓缩液，以0.9%氯化钠注射液稀释至所需给药体积。','仅可使用0.9%氯化钠注射液稀释。'],storage:['原瓶2–8℃避光。','稀释后优先立即使用；未立即使用：2–8℃≤24 h，室温≤25℃≤8 h。'],infusion:['输液器无特殊要求。','首次输注≥60 min；耐受良好后续可缩短，但≥30 min。'],warnings:['仅用0.9% NaCl稀释','稀释后限时使用']},
BEVA_AVASTIN:{prep:['以0.9%氯化钠注射液稀释至所需给药体积。','终浓度1.4–16.5 mg/mL。'],storage:['2–8℃避光保存。','不可冷冻，不得振摇。','稀释后2–8℃≤24 h。'],infusion:['输液器无特殊要求。','首次输注90 min；首次耐受良好后第二次可60 min。'],warnings:['不可冷冻','不得振摇','终浓度1.4–16.5 mg/mL']},
BEVA_DYT:{prep:['无菌操作，抽取所需本品，以0.9%氯化钠注射液稀释。','终浓度1.4–16.5 mg/mL。'],storage:['2–8℃避光；配制后优先立即使用。','不能立即使用时2–8℃≤24 h。'],infusion:['输液器无特殊要求。'],warnings:['不得与右旋糖/葡萄糖溶液同时或混合给药','不得静脉推注或快速注射','终浓度1.4–16.5 mg/mL']},
DARA:{prep:['先从输液袋移除与本品等体积的0.9% NaCl，再加入所需本品稀释。'],storage:['原瓶2–8℃避光，不可冷冻。','稀释液室温15–25℃下须在15 h内完成输注（含输注时间）；或2–8℃避光≤24 h。'],infusion:['使用0.2/0.22 μm低蛋白结合PES过滤器。','可使用PU/PBD/PVC/PP/PE输液装置。'],warnings:['不可冷冻','0.2/0.22 μm PES滤器','室温15 h内完成输注']},
DURVA:{prep:['0.9% NaCl或5%葡萄糖注射液稀释。','轻轻翻转混匀，不得摇动。','最终浓度1–15 mg/mL。'],storage:['2–8℃避光。','稀释后：2–8℃≤24 h；室温≤25℃≤8 h。'],infusion:['输注时间>60 min。','使用0.2/0.22 μm低蛋白结合率无菌管内滤器。'],warnings:['不得摇动','最终浓度1–15 mg/mL','0.2/0.22 μm低蛋白结合滤器']},
BRENTUX_50:{prep:['每瓶用10.5 mL注射用水复溶，不得振摇；复溶后5 mg/mL。','取所需复溶液稀释，推荐体积150 mL；可用0.9% NaCl、5%葡萄糖或乳酸林格液。','终浓度0.4–1.2 mg/mL。'],storage:['2–8℃避光，不可冷冻。','复溶/稀释后优先立即使用；不能立即使用时2–8℃≤24 h。'],infusion:['输液器无特殊要求。','静脉输注≥30 min；使用专用静脉通路。'],warnings:['不得振摇','不可冷冻','不得静脉推注或快速滴注','不可与其他药物混合']}
};
const images={ATEZO:'./assets/ATEZO.svg',BEVA_AVASTIN:'./assets/BEVA_AVASTIN.svg',BEVA_DYT:'./assets/BEVA_DAC.svg',DARA:'./assets/DARA.svg',DURVA:'./assets/DURVA.svg',BRENTUX_50:'./assets/BRENTUX_50.svg'};
const markRe=/(不得振摇|不得摇动|不可冷冻|不得静脉推注或快速滴注|不得静脉推注或快速注射|不可与其他药物混合|仅可使用0\.9%氯化钠注射液稀释|仅用0\.9% NaCl稀释|0\.2\/0\.22 μm|1–15 mg\/mL|1\.4–16\.5 mg\/mL|0\.4–1\.2 mg\/mL|5 mg\/mL|10\.5 mL|150 mL|≥60 min|>60 min|≥30 min|≤24 h|≤8 h|15 h|2–8℃|0\.9% NaCl|5%葡萄糖|乳酸林格液)/g;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const marked=s=>esc(s).replace(markRe,'<span class="critical">$1</span>');
const list=a=>`<ul>${(a||[]).map(x=>`<li>${marked(x)}</li>`).join('')}</ul>`;
function ensureUi(){
 const head=document.querySelector('.top .sub:last-child');if(head)head.textContent='知识库 v0.6 · 6个药品条目 · 一页速览卡';
 const third=document.querySelector('#home .tile:nth-of-type(3)');if(third){third.onclick=()=>{renderKnowledge();go('knowledge')};third.querySelector('b').textContent='药品知识库';third.querySelector('p').textContent='6个一页式速览卡，含药品图片'}
 const grid=document.querySelector('#home .grid');const status=grid?.querySelector('.status');if(grid&&status&&!document.querySelector('[data-v06-settings]')){const t=document.createElement('div');t.className='tile panel';t.dataset.v06Settings='1';t.innerHTML='<div class="icon">⚙</div><div><b>AI / API 设置</b><p>自定义外部模型 Base URL、Key 与模型名称</p></div>';t.onclick=()=>{loadApi();go('settings')};grid.insertBefore(t,status)}
 if(!document.getElementById('knowledge')){const s=document.createElement('section');s.id='knowledge';s.className='screen';s.innerHTML='<div class="bar"><button class="back" onclick="go(\'home\')">← 返回</button><h2>药品知识库</h2></div><div class="search panel"><div class="searchrow"><input id="kq" placeholder="搜索药名、商品名、英文名、规格" oninput="renderKnowledge()"><button class="btn primary" onclick="renderKnowledge()">搜索</button></div><div id="knowledgeList" class="list"></div></div>';document.querySelector('main').appendChild(s)}
 if(!document.getElementById('settings')){const s=document.createElement('section');s.id='settings';s.className='screen';s.innerHTML='<div class="bar"><button class="back" onclick="go(\'home\')">← 返回</button><h2>AI / API 设置</h2></div><div class="settings-grid"><div class="panel settings-card"><h3>外部 AI 服务</h3><label>API Base URL<input id="apiBase" placeholder="https://api.example.com/v1"></label><label>API Key<input id="apiKey" type="password" placeholder="仅保存在本机浏览器"></label><label>Model<input id="apiModel" placeholder="模型名称"></label><div class="actions"><button class="btn primary" onclick="saveApi()">保存</button><button class="btn" onclick="testApiV06()">测试连接</button></div><div id="apiStatus" class="small" style="margin-top:10px"></div></div><div class="panel settings-card"><h3>运行策略</h3><p><b>识药、搜索、药品卡均本地优先。</b></p><p>外部 AI 用于当前药品问答，以及后续“说明书 → 药品卡草稿”。</p><div class="warning">网页 Demo 的 Key 仅适合本机测试；正式 APK 使用 Android Keystore，并建议接医院统一网关。</div></div></div>';document.querySelector('main').appendChild(s)}
 if(!document.getElementById('aiDrawer')){document.body.insertAdjacentHTML('beforeend','<aside id="aiDrawer" class="ai-drawer"><div class="ai-head"><div><b>AI 问答</b><div class="small" id="aiContext">当前药品上下文</div></div><button class="btn ghost" onclick="closeAiDrawer()">关闭</button></div><div id="aiChat" class="ai-chat"><div class="assistant-msg">可以直接问当前药品的调配、稳定性、输注要求或关键提醒。</div></div><div class="qa-chips"><button onclick="quickAsk(\'怎么配？\')">怎么配？</button><button onclick="quickAsk(\'稀释后能保存多久？\')">保存多久？</button><button onclick="quickAsk(\'输注有什么要求？\')">输注要求</button></div><div class="ai-input"><button class="mic" onclick="startVoiceQa()">🎤</button><input id="aiq" placeholder="输入问题或点击麦克风"><button class="btn primary" onclick="askAi()">发送</button></div></aside><div id="aiBackdrop" class="ai-backdrop" onclick="closeAiDrawer()"></div>')}
}
window.openDrug=function(id){const d=drugs.find(x=>x.id===id)||drugs[0],q=quick[d.id]||{prep:[d.prep],storage:[d.storage],infusion:[d.infusion],warnings:d.warnings};currentDrug=d.id;document.getElementById('drugCard').innerHTML=`<div class="drughead panel"><div class="drugtitle"><h1>${esc(d.name)}<span class="quick-badge">一页速览</span></h1><p>${esc(d.en)}${d.brand?' · '+esc(d.brand):''}${d.maker?' · '+esc(d.maker):''}</p></div><div class="spec">${marked(d.strength)}</div><div class="drug-photo-wrap"><img class="drug-photo" src="${images[d.id]||''}" alt="${esc(d.name)}"></div></div><div class="info panel blue"><h3>调配方法</h3>${list(q.prep)}</div><div class="info panel purple"><h3>输注 / 输液器</h3>${list(q.infusion)}</div><div class="info panel green"><h3>稳定性 / 贮存</h3>${list(q.storage)}</div><div class="info panel red"><h3>关键提醒</h3>${list(q.warnings)}</div><div class="footer panel"><div><b>来源：</b>${esc(d.source||'院内PIVAS纸质药品卡（试验录入）')}<span class="small"> · 正式使用前核对现行说明书版本</span></div><div class="actions"><button class="btn" onclick="toast(\'原始说明书PDF后续绑定到知识库\')">查看说明书</button><button class="btn primary" onclick="openAiDrawer()">询问 AI</button></div></div>`;go('drug')};
window.openAiDrawer=function(){const d=drugs.find(x=>x.id===currentDrug);document.getElementById('aiContext').textContent=d?`${d.name} · ${d.strength}`:'当前药品上下文';document.getElementById('aiDrawer').classList.add('show');document.getElementById('aiBackdrop').classList.add('show')};window.closeAiDrawer=function(){document.getElementById('aiDrawer')?.classList.remove('show');document.getElementById('aiBackdrop')?.classList.remove('show')};
function addChat(role,text){const b=document.getElementById('aiChat'),e=document.createElement('div');e.className=role==='user'?'user-msg':'assistant-msg';e.textContent=text;b.appendChild(e);b.scrollTop=b.scrollHeight}
function localAnswer(d,q){if(/室温|多久|保存|稳定|贮存|冷藏/.test(q))return quick[d.id].storage.join('；');if(/输注|滤器|输液器|分钟/.test(q))return quick[d.id].infusion.join('；');if(/稀释|调配|怎么配|溶媒|复溶/.test(q))return quick[d.id].prep.join('；');if(/注意|振摇|摇动|冷冻|警告|提醒/.test(q))return quick[d.id].warnings.join('；');return '当前速览卡没有足够信息直接回答。请查看原说明书，或配置外部AI后继续问答。'}
const getApi=()=>{try{return JSON.parse(localStorage.getItem('pivas_api')||'{}')}catch{return {}}};window.loadApi=function(){const s=getApi();setTimeout(()=>{if(document.getElementById('apiBase')){apiBase.value=s.base||'';apiKey.value=s.key||'';apiModel.value=s.model||''}},0)};window.saveApi=function(){const s={base:apiBase.value.trim(),key:apiKey.value.trim(),model:apiModel.value.trim()};localStorage.setItem('pivas_api',JSON.stringify(s));apiStatus.textContent='已保存到本机浏览器';toast('API设置已保存')};
async function remoteAnswer(d,q){const s=getApi();if(!s.base||!s.key||!s.model)return null;const r=await fetch(s.base.replace(/\/$/,'')+'/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+s.key},body:JSON.stringify({model:s.model,temperature:.1,messages:[{role:'system',content:'你是PIVAS药品卡问答助手，只能依据给定药品卡回答；无依据时明确说明。药品卡：'+JSON.stringify({name:d.name,strength:d.strength,quick:quick[d.id]})},{role:'user',content:q}]})});if(!r.ok)throw new Error('HTTP '+r.status);const j=await r.json();return j.choices?.[0]?.message?.content||'未收到回答'}
window.askAi=async function(){const d=drugs.find(x=>x.id===currentDrug),i=document.getElementById('aiq'),q=(i?.value||'').trim();if(!d||!q)return;openAiDrawer();addChat('user',q);i.value='';try{addChat('assistant',(await remoteAnswer(d,q))||localAnswer(d,q))}catch(e){addChat('assistant','外部AI调用失败，已切换本地卡片回答：'+localAnswer(d,q))}};window.quickAsk=function(q){document.getElementById('aiq').value=q;askAi()};window.startVoiceQa=function(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('当前浏览器不支持语音识别');return}const r=new SR();r.lang='zh-CN';r.onresult=e=>{document.getElementById('aiq').value=e.results[0][0].transcript;askAi()};r.onerror=e=>toast('语音识别失败：'+e.error);r.start();toast('请说出问题')};
window.renderKnowledge=function(){const q=n(document.getElementById('kq')?.value||'');const a=!q?drugs:drugs.filter(d=>n([d.name,d.brand,d.en,d.strength,d.maker,...d.aliases].join(' ')).includes(q)||scoreDrug(d,q)>.42);document.getElementById('knowledgeList').innerHTML=a.map(d=>`<div class="drugrow"><div><h3>${esc(d.name)}</h3><p>${esc(d.brand||'—')} · ${esc(d.strength)}</p></div><button class="btn" onclick="openDrug('${d.id}')">打开速览卡</button></div>`).join('')};
window.testApiV06=async function(){saveApi();const s=getApi();apiStatus.textContent='测试中…';try{const r=await fetch(s.base.replace(/\/$/,'')+'/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+s.key},body:JSON.stringify({model:s.model,temperature:0,messages:[{role:'user',content:'仅回复OK'}]})});apiStatus.textContent=r.ok?'连接成功':'连接失败：HTTP '+r.status}catch(e){apiStatus.textContent='连接失败：'+e.message}};
ensureUi();
})();