(()=>{
const HKEY='pivas_history',DKEY='pivas_drafts';
const getJson=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}};
const saveJson=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function logAction(type,drugId='',detail=''){const h=getJson(HKEY,[]);h.unshift({time:new Date().toISOString(),type,drugId,detail});saveJson(HKEY,h.slice(0,100))}
function addHomeTile(label,desc,icon,fn,attr){const grid=document.querySelector('#home .grid'),status=grid?.querySelector('.status');if(!grid||!status||document.querySelector(`[${attr}]`))return;const t=document.createElement('div');t.className='tile panel';t.setAttribute(attr,'1');t.innerHTML=`<div class="icon">${icon}</div><div><b>${label}</b><p>${desc}</p></div>`;t.onclick=fn;grid.insertBefore(t,status)}
function addScreen(id,title,body){if(document.getElementById(id))return;const s=document.createElement('section');s.id=id;s.className='screen';s.innerHTML=`<div class="bar"><button class="back" onclick="go('home')">← 返回</button><h2>${title}</h2></div>${body}`;document.querySelector('main').appendChild(s)}
function ensureV08(){
 const head=document.querySelector('.top .sub:last-child');if(head)head.textContent='知识库 v0.8 · 6个药品条目 · 语音/建卡/历史 PoC';
 addHomeTile('语音搜药','说出药名、商品名或规格，转写后进入本地匹配','🎙',()=>{go('voice');setTimeout(()=>startVoiceSearch(),120)},'data-v08-voice');
 addHomeTile('建卡 / 审核','导入说明书文件，生成 Draft，核对来源后发布','＋',()=>{renderBuilder();go('builder')},'data-v08-builder');
 addHomeTile('使用历史','查看搜索、识别、建卡与发布的非患者级记录','◷',()=>{renderHistory();go('history')},'data-v08-history');
 addScreen('voice','语音搜索',`<div class="panel v08-card"><div class="voice-orb" id="voiceOrb">🎙</div><h3>说出药名 / 商品名 / 规格</h3><p class="small">例如“维布妥昔单抗 50 毫克”。语音只是搜索输入，不绕过品规确认。</p><div id="voiceText" class="voice-text">等待语音输入</div><div class="actions"><button class="btn primary" onclick="startVoiceSearch()">开始说话</button><button class="btn" onclick="voiceToSearch()">用转写文字搜索</button></div><div id="voiceCandidates" class="list"></div></div>`);
 addScreen('builder','说明书导入 / AI 建卡',`<div class="builder-grid"><div class="panel v08-card"><h3>1. 导入资料</h3><input id="leafletFile" type="file" accept=".pdf,.txt,.md" onchange="renderBuilder()"><label>药品名称<input id="draftName" placeholder="例如：注射用××"></label><label>规格<input id="draftStrength" placeholder="例如：50 mg/瓶"></label><label>来源/版本<input id="draftSource" placeholder="说明书版本或院内卡来源"></label><button class="btn primary" onclick="generateDraft()">生成 Draft</button><p class="small">未配置外部 AI 时仅生成演示草稿；不会伪装成临床级自动提取。</p></div><div class="panel v08-card"><h3>2. Draft / 审核</h3><div id="draftStatus" class="warning">尚未生成草稿</div><label>调配方法<textarea id="draftPrep"></textarea></label><label>稳定性 / 贮存<textarea id="draftStorage"></textarea></label><label>输注 / 输液器<textarea id="draftInfusion"></textarea></label><label>关键提醒<textarea id="draftWarnings"></textarea></label><label class="review-check"><input id="sourceChecked" type="checkbox"> 我已核对原始来源/说明书</label><div class="actions"><button class="btn" onclick="saveDraft()">保存 Draft</button><button class="btn primary" onclick="publishDraft()">审核并发布</button></div></div></div>`);
 addScreen('history','使用历史',`<div class="panel v08-card"><div class="actions" style="justify-content:flex-end"><button class="btn ghost" onclick="clearHistory()">清空历史</button></div><div id="historyList" class="list"></div></div>`);
 enhanceSettings();enhanceSearch();enhanceDrugLogging();updateStatus();
}
function updateStatus(){const status=document.querySelector('#home .status');if(status&&!document.getElementById('voiceCap')){const span=document.createElement('span');span.id='voiceCap';const ok=!!(window.SpeechRecognition||window.webkitSpeechRecognition);span.innerHTML=`<i class="dot" style="background:${ok?'#18aa73':'#d99b22'}"></i>语音搜索 ${ok?'可用':'浏览器不支持，文字兜底'}`;status.appendChild(span)}}
let lastVoice='';
window.startVoiceSearch=function(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){document.getElementById('voiceText').textContent='当前浏览器不支持 Web Speech API，请使用手动搜索。';return}const r=new SR();r.lang='zh-CN';r.interimResults=true;r.continuous=false;const orb=document.getElementById('voiceOrb');orb?.classList.add('listening');r.onresult=e=>{let txt='';for(let i=e.resultIndex;i<e.results.length;i++)txt+=e.results[i][0].transcript;lastVoice=txt.trim();document.getElementById('voiceText').textContent=lastVoice||'正在听…';renderVoiceCandidates(lastVoice)};r.onend=()=>orb?.classList.remove('listening');r.onerror=e=>{orb?.classList.remove('listening');document.getElementById('voiceText').textContent='语音识别失败：'+e.error};r.start()};
function renderVoiceCandidates(text){if(!text)return;const rs=rank(text).filter(x=>x.score>.25).slice(0,4),box=document.getElementById('voiceCandidates');box.innerHTML=rs.map(x=>`<div class="drugrow"><div><h3>${x.d.name}</h3><p>${x.d.brand||'—'} · ${x.d.strength} · 匹配${Math.round(x.score*100)}%</p></div><button class="btn primary" onclick="logVoiceOpen('${x.d.id}')">打开</button></div>`).join('')||'<div class="small">没有可靠候选，请转到手动搜索。</div>'}
window.voiceToSearch=function(){document.getElementById('q').value=lastVoice;logAction('语音搜索','',lastVoice);go('search');renderSearch()};
window.logVoiceOpen=function(id){logAction('语音搜索',id,lastVoice);openDrug(id)};
function enhanceSearch(){const old=window.renderSearch;if(typeof old==='function')window.renderSearch=function(){old();const q=document.getElementById('q')?.value?.trim();if(q)sessionStorage.setItem('pivas_last_search',q)}}
function enhanceDrugLogging(){const old=window.openDrug;if(typeof old==='function'&&!old.__v08){const f=function(id){logAction('打开药品卡',id,sessionStorage.getItem('pivas_last_search')||'');return old(id)};f.__v08=true;window.openDrug=f}}
function enhanceSettings(){const card=document.querySelector('#settings .settings-card');if(!card||document.getElementById('apiTemp'))return;const anchor=card.querySelector('.actions');const html=`<div class="setting-row"><label>Temperature<input id="apiTemp" type="number" min="0" max="2" step="0.1" value="0.1"></label><label>Timeout (s)<input id="apiTimeout" type="number" min="5" max="120" value="30"></label></div><label class="review-check"><input id="aiEnabled" type="checkbox" checked> 启用外部 AI</label><label class="review-check"><input id="visionEnabled" type="checkbox"> 视觉兜底（默认关闭）</label>`;anchor.insertAdjacentHTML('beforebegin',html);const oldLoad=window.loadApi,oldSave=window.saveApi;window.loadApi=function(){oldLoad?.();const s=getJson('pivas_api',{});setTimeout(()=>{if(apiTemp){apiTemp.value=s.temperature??.1;apiTimeout.value=s.timeout??30;aiEnabled.checked=s.enabled!==false;visionEnabled.checked=!!s.vision}},0)};window.saveApi=function(){const s={base:apiBase.value.trim(),key:apiKey.value.trim(),model:apiModel.value.trim(),temperature:Number(apiTemp.value||.1),timeout:Number(apiTimeout.value||30),enabled:aiEnabled.checked,vision:visionEnabled.checked};saveJson('pivas_api',s);apiStatus.textContent='已保存到本机浏览器（PoC）';toast('API设置已保存')}}
window.renderBuilder=function(){setTimeout(()=>{const f=document.getElementById('leafletFile')?.files?.[0];if(f)document.getElementById('draftStatus').textContent=`已选择：${f.name} · ${(f.size/1024).toFixed(1)} KB · 等待生成 Draft`},0)};
window.generateDraft=function(){const name=draftName.value.trim(),strength=draftStrength.value.trim(),source=draftSource.value.trim(),file=leafletFile.files?.[0];if(!name){toast('请先填写药品名称');return}draftPrep.value='[DRAFT] 请根据原始说明书核对复溶、稀释液、体积与终浓度。';draftStorage.value='[DRAFT] 请核对原瓶及复溶/稀释后的温度、避光和稳定时间。';draftInfusion.value='[DRAFT] 请核对输注时间、滤器及管路要求。';draftWarnings.value='[DRAFT] 仅保留 PIVAS 操作高优先级提醒。';draftStatus.textContent=`DRAFT · ${name}${strength?' · '+strength:''}${file?' · '+file.name:''} · 尚未发布`;logAction('生成Draft','',name+' '+source)};
function draftObj(status='DRAFT'){return {id:'WEB_'+Date.now(),name:draftName.value.trim(),strength:draftStrength.value.trim(),source:draftSource.value.trim(),prep:draftPrep.value.trim(),storage:draftStorage.value.trim(),infusion:draftInfusion.value.trim(),warnings:draftWarnings.value.split(/[；\n]+/).map(x=>x.trim()).filter(Boolean),status,updatedAt:new Date().toISOString()}}
window.saveDraft=function(){const d=draftObj('DRAFT');if(!d.name){toast('请填写药品名称');return}const a=getJson(DKEY,[]);a.unshift(d);saveJson(DKEY,a.slice(0,30));draftStatus.textContent='DRAFT 已保存到当前浏览器';logAction('保存Draft',d.id,d.name);toast('Draft已保存')};
window.publishDraft=function(){if(!sourceChecked.checked){toast('必须先确认已核对原始来源');return}const d=draftObj('PUBLISHED_DEMO');if(!d.name||!d.source){toast('发布前必须填写药品名称和来源/版本');return}const a=getJson(DKEY,[]);a.unshift(d);saveJson(DKEY,a.slice(0,30));draftStatus.textContent='PUBLISHED_DEMO · 已审核发布到 Web Demo 本地存储';logAction('审核发布',d.id,d.name);toast('已发布到 Web Demo 本地知识库')};
window.renderHistory=function(){setTimeout(()=>{const h=getJson(HKEY,[]),box=document.getElementById('historyList');box.innerHTML=h.length?h.map(x=>`<div class="history-row"><div><b>${x.type}</b><div class="small">${new Date(x.time).toLocaleString()}${x.drugId?' · '+x.drugId:''}</div></div><div class="small">${String(x.detail||'').replace(/[<>]/g,'')}</div></div>`).join(''):'<div class="small">暂无记录。这里不会保存患者信息。</div>'},0)};
window.clearHistory=function(){localStorage.removeItem(HKEY);renderHistory();toast('历史已清空')};
document.addEventListener('DOMContentLoaded',ensureV08);if(document.readyState!=='loading')ensureV08();
})();