(()=>{
const Core=window.PivasAgentCore, AKEY='pivas_agent_runs';let agent={runId:'',sourceText:'',sourceName:'',fields:{},missingFields:[],conflicts:[],supplementSearched:false,validated:false,logs:[]};
const fieldNames={prep:'调配方法',storage:'稳定性 / 贮存',infusion:'输注 / 输液器',warnings:'关键提醒'};
const jget=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}},jset=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function api(){try{return JSON.parse(localStorage.getItem('pivas_api')||'{}')}catch{return {}}}
function log(s){agent.logs.push(new Date().toLocaleTimeString()+'  '+s);renderAgent()}
function screen(){if(document.getElementById('agent'))return;const s=document.createElement('section');s.id='agent';s.className='screen';s.innerHTML=`<div class="bar"><button class="back" onclick="go('home')">← 返回</button><h2>PIVAS 药品知识维护智能体 <span class="agent-badge">Agent v0.9</span></h2></div><div class="agent-shell"><div class="panel agent-card"><h3>任务输入</h3><input id="agentFile" type="file" accept=".txt,.md,.pdf" onchange="agentFileChanged()"><label>药品名称<input id="agentName" placeholder="例如：注射用维布妥昔单抗"></label><label>规格<input id="agentStrength" placeholder="50 mg/瓶"></label><label>主来源/版本<input id="agentSource" placeholder="院内卡 / 说明书版本"></label><label>说明书文本 <span class="agent-note">TXT/MD自动读取；PDF文本版可尝试浏览器解析，扫描版需OCR</span><textarea id="agentText" class="agent-source-text" placeholder="也可以直接粘贴说明书相关章节"></textarea></label><div class="agent-actions"><button class="btn primary" onclick="runKnowledgeAgent()">▶ 启动智能体</button><button class="btn" onclick="resetKnowledgeAgent()">重置</button></div><h3>智能体工作流</h3><div id="agentSteps" class="agent-steps"></div><div class="agent-progress"><i id="agentProgress"></i></div><h3>运行日志</h3><div id="agentLog" class="agent-log">等待启动…</div></div><div class="panel agent-card"><div class="actions" style="justify-content:space-between"><h3 style="margin:0">结构化 Draft + 证据</h3><span id="agentRunBadge" class="agent-badge">未运行</span></div><div id="agentFields" class="evidence-grid"></div><div id="agentGate" class="publish-gate blocked">尚未形成可审核 Draft</div><div class="agent-actions" style="margin-top:10px"><button class="btn" onclick="saveAgentDraft()">保存 Draft</button><button class="btn primary" onclick="publishAgentDraft()">药师审核并发布</button></div><label class="review-check"><input id="agentReviewed" type="checkbox"> 药师已逐项核对主来源、补充证据与冲突</label><div class="external-box agent-note" style="margin-top:10px"><b>B 方案：</b>智能体允许提出并整理外部补充证据，但外部资料永远标记为“补充”，不能单独支撑正式发布；本 Web Demo 不具备自主联网检索执行器，正式 Agent 后端再接官方检索工具。</div></div></div>`;document.querySelector('main').appendChild(s)}
function install(){screen();const tile=document.querySelector('[data-v08-builder]');if(tile){tile.querySelector('b').textContent='知识维护智能体';tile.querySelector('p').textContent='说明书→提取→缺口→补证→冲突→药师审核';tile.onclick=()=>{go('agent');renderAgent()}}const sub=document.querySelector('.top .sub:last-child');if(sub)sub.textContent='知识库 v0.9 · 6个药品条目 · Knowledge Agent PoC'}
const steps=[['PARSE_SOURCE','解析主来源'],['EXTRACT_FIELDS','结构化提取'],['SEARCH_SUPPLEMENT','识别缺口 / 补充证据'],['RESOLVE_CONFLICT','冲突检查'],['VALIDATE_DRAFT','证据校验'],['PHARMACIST_REVIEW','药师审核']];
function statusFor(code){const cur=Core.nextAgentStep({parsed:!!agent.sourceText,extracted:Object.keys(agent.fields).length>0,missingFields:agent.missingFields,supplementSearched:agent.supplementSearched,conflicts:agent.conflicts,validated:agent.validated});const ci=steps.findIndex(x=>x[0]===cur),i=steps.findIndex(x=>x[0]===code);if(agent.conflicts.length&&code==='RESOLVE_CONFLICT')return'block';if(i<ci)return'done';if(i===ci)return'active';return''}
function renderAgent(){if(!document.getElementById('agentSteps'))return;agentSteps.innerHTML=steps.map(x=>`<div class="agent-step ${statusFor(x[0])}"><i class="agent-dot"></i><span>${x[1]}</span></div>`).join('');const cur=Core.nextAgentStep({parsed:!!agent.sourceText,extracted:Object.keys(agent.fields).length>0,missingFields:agent.missingFields,supplementSearched:agent.supplementSearched,conflicts:agent.conflicts,validated:agent.validated}),idx=Math.max(0,steps.findIndex(x=>x[0]===cur));agentProgress.style.width=Math.min(100,(idx+1)/steps.length*100)+'%';agentLog.textContent=agent.logs.join('\n')||'等待启动…';agentRunBadge.textContent=agent.runId||'未运行';agentFields.innerHTML=Object.entries(fieldNames).map(([k,n])=>{const f=agent.fields[k]||{text:'',evidence:[]};return `<div class="field-evidence agent-field"><h4>${n}</h4><textarea id="af_${k}" oninput="agentFieldEdit('${k}')">${esc(f.text||'')}</textarea>${(f.evidence||[]).map(e=>`<div class="evidence-item ${e.role==='supplemental'?'supp':''}"><span class="agent-badge ${e.role==='supplemental'?'supp':''}">${e.role==='supplemental'?'外部补充':'主来源'}</span> ${esc(e.locator||'')}<br>${esc(e.quote||'')}</div>`).join('')}${f.conflict?'<div class="evidence-item conflict"><span class="agent-badge block">冲突</span> 需要药师裁决</div>':''}</div>`}).join('');const v=Core.validateAgentDraft({fields:agent.fields});agentGate.className='publish-gate '+(v.canPublish&&!agent.conflicts.length?'':'blocked');agentGate.innerHTML=v.canPublish&&!agent.conflicts.length?'✓ 已通过程序证据门槛，等待药师人工审核':'⛔ '+(v.blockers.concat(agent.conflicts).join('；')||'尚未完成证据校验')}
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
window.agentFieldEdit=k=>{agent.fields[k].text=document.getElementById('af_'+k).value;agent.validated=false;renderAgent()};
window.agentFileChanged=async()=>{const f=agentFile.files?.[0];if(!f)return;agent.sourceName=f.name;if(/\.(txt|md)$/i.test(f.name)){agentText.value=await f.text();agent.sourceText=agentText.value;log('已读取文本文件：'+f.name)}else if(/\.pdf$/i.test(f.name)){agentText.placeholder='PDF 已选择。v0.9 Web 前端不伪造解析结果：请粘贴文本，或在正式 Agent 后端接 PDF 解析/OCR。';log('已选择 PDF：'+f.name+'；等待 PDF 解析/OCR 工具链')}};
async function llmExtract(text){const s=api();if(s.enabled===false||!s.base||!s.key||!s.model)throw new Error('未配置可用外部 AI');const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),Number(s.timeout||30)*1000);const schema=`只返回JSON。fields含prep/storage/infusion/warnings。每个字段格式 {text:string,evidence:[{role:"primary",locator:string,quote:string}],conflict:boolean}。只能从UPLOAD文本抽取，找不到就text为空。quote必须是UPLOAD中的短原文证据。另返回missingFields数组。`;try{const r=await fetch(s.base.replace(/\/$/,'')+'/chat/completions',{method:'POST',signal:ctl.signal,headers:{'Content-Type':'application/json','Authorization':'Bearer '+s.key},body:JSON.stringify({model:s.model,temperature:Number(s.temperature??.1),messages:[{role:'system',content:'你是PIVAS药品知识维护智能体的结构化提取器。'+schema},{role:'user',content:`药品：${agentName.value}\n规格：${agentStrength.value}\n主来源：${agentSource.value}\nUPLOAD:\n${text.slice(0,45000)}`}]})});if(!r.ok)throw new Error('AI HTTP '+r.status);const j=await r.json(),raw=j.choices?.[0]?.message?.content||'';return JSON.parse(raw.replace(/^```json\s*|```$/g,'').trim())}finally{clearTimeout(timer)}}
window.runKnowledgeAgent=async()=>{agent={runId:'RUN-'+new Date().toISOString().replace(/[-:.TZ]/g,'').slice(0,14),sourceText:agentText.value.trim(),sourceName:agentFile.files?.[0]?.name||'',fields:{},missingFields:[],conflicts:[],supplementSearched:false,validated:false,logs:[]};if(!agentName.value.trim()){toast('请填写药品名称');return}if(!agent.sourceText){toast('请提供可读取的说明书文本');log('阻断：没有可读取的主来源文本');return}log('Step 1/6 解析用户上传/粘贴的主来源');log('Step 2/6 调用结构化提取器');try{const out=await llmExtract(agent.sourceText);agent.fields=out.fields||{};for(const k of Object.keys(fieldNames)){agent.fields[k]=agent.fields[k]||{text:'',evidence:[],conflict:false};agent.fields[k].evidence=(agent.fields[k].evidence||[]).map(e=>Core.normalizeEvidenceItem({...e,sourceType:'uploaded'}))}agent.missingFields=out.missingFields||Object.keys(fieldNames).filter(k=>!String(agent.fields[k]?.text||'').trim());log('已完成主来源提取；缺口：'+(agent.missingFields.join(', ')||'无'));if(agent.missingFields.length){log('Step 3/6 形成外部补证任务。Web Demo 暂不自动联网执行，等待正式检索工具接入');agent.supplementSearched=true}else{agent.supplementSearched=true}agent.conflicts=Object.entries(agent.fields).filter(([,f])=>f.conflict).map(([k])=>k+' 存在来源冲突');log('Step 4/6 冲突检查：'+(agent.conflicts.length?agent.conflicts.join('；'):'未发现模型标记冲突'));const v=Core.validateAgentDraft({fields:agent.fields});agent.validated=v.canPublish;log('Step 5/6 证据校验：'+(v.canPublish?'通过程序门槛':'阻断 '+v.blockers.join('；')));log('Step 6/6 等待药师人工审核');saveRun();renderAgent()}catch(e){log('智能体停止：'+e.message);toast('智能体未完成：'+e.message)}};
function saveRun(){const a=jget(AKEY,[]);a.unshift({...agent,name:agentName.value.trim(),strength:agentStrength.value.trim(),source:agentSource.value.trim()});jset(AKEY,a.slice(0,20))}
window.saveAgentDraft=()=>{saveRun();toast('Agent Draft 已保存')};
window.publishAgentDraft=()=>{for(const k of Object.keys(fieldNames)){if(document.getElementById('af_'+k))agent.fields[k].text=document.getElementById('af_'+k).value}const v=Core.validateAgentDraft({fields:agent.fields});if(!v.canPublish||agent.conflicts.length){toast('证据门槛未通过，禁止发布');renderAgent();return}if(!agentReviewed.checked){toast('必须由药师逐项审核后才能发布');return}const a=jget('pivas_drafts',[]);a.unshift({id:'AGENT_'+Date.now(),name:agentName.value.trim(),strength:agentStrength.value.trim(),source:agentSource.value.trim(),fields:agent.fields,status:'PUBLISHED_DEMO',agentRunId:agent.runId,updatedAt:new Date().toISOString()});jset('pivas_drafts',a.slice(0,30));toast('药师审核完成：已发布到 Demo 本地知识库');log('发布：药师审核通过')};
window.resetKnowledgeAgent=()=>{agent={runId:'',sourceText:'',sourceName:'',fields:{},missingFields:[],conflicts:[],supplementSearched:false,validated:false,logs:[]};agentText.value='';agentReviewed.checked=false;renderAgent()};
document.addEventListener('DOMContentLoaded',install);if(document.readyState!=='loading')install();
})();